// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6KKwZWfXgxMw1NZK_kcqsjN-Yr8PRM-U',
    appId: '1:654998396295:web:69367abd3101a2bd3a4722',
    messagingSenderId: '654998396295',
    projectId: 'fcm-project-nabia',
    authDomain: 'fcm-project-nabia.firebaseapp.com',
    storageBucket: 'fcm-project-nabia.firebasestorage.app',
    measurementId: 'G-YR8VQHEMCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1FnnjhE-DjZMTECpjqC0mx2degzZaYkY',
    appId: '1:654998396295:android:80b0c16eb86dd44c3a4722',
    messagingSenderId: '654998396295',
    projectId: 'fcm-project-nabia',
    storageBucket: 'fcm-project-nabia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1NqcLTh0PNmbZ9y_GBtA_YiiWik2_n_g',
    appId: '1:654998396295:ios:712c1146c309a0273a4722',
    messagingSenderId: '654998396295',
    projectId: 'fcm-project-nabia',
    storageBucket: 'fcm-project-nabia.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1NqcLTh0PNmbZ9y_GBtA_YiiWik2_n_g',
    appId: '1:654998396295:ios:712c1146c309a0273a4722',
    messagingSenderId: '654998396295',
    projectId: 'fcm-project-nabia',
    storageBucket: 'fcm-project-nabia.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6KKwZWfXgxMw1NZK_kcqsjN-Yr8PRM-U',
    appId: '1:654998396295:web:04abcceadd9cc7cb3a4722',
    messagingSenderId: '654998396295',
    projectId: 'fcm-project-nabia',
    authDomain: 'fcm-project-nabia.firebaseapp.com',
    storageBucket: 'fcm-project-nabia.firebasestorage.app',
    measurementId: 'G-ZZ1ECLB8VK',
  );
}
